# Generated by Django 3.1.3 on 2021-10-03 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('barbearia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barbeiro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('telefone', models.CharField(max_length=200)),
                ('barbearia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='barbearia.barbearia')),
            ],
        ),
        migrations.CreateModel(
            name='BarbeiroServico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('barbeiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicos', to='barbeiro.barbeiro')),
            ],
        ),
    ]
